-- Obtener fecha actual
SELECT SYSDATE FROM DUAL;           -- [FECHA Y HORA EN EL SERVIDOR]
SELECT CURRENT_DATE FROM DUAL;      
SELECT current_timestamp FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
-- Obtener primer dia del presente mes/año
SELECT TRUNC(SYSDATE, 'MM'/*'MONTH'*/) FROM DUAL; --mes
SELECT TRUNC(SYSDATE, 'YY'/*'YYYY'*/) FROM DUAL; --año
-- Obtener último dia del presente mes/año
SELECT LAST_DAY(SYSDATE) FROM DUAL; --mes
SELECT TO_DATE(EXTRACT (YEAR FROM SYSDATE)||'12/31', 'YYYY/MM/DD' ) FROM DUAL; --año
-- Para obtener valores entre fechas
SELECT ...
  FROM ...
 WHERE 1 = 1
   AND VALUE >= TO_DATE(&p_start_date, 'YYYY/MM/DD HH24:MI:SS'/*'YYYY/MM/DD'*/)
   AND VALUE <  TO_DATE(&p_end_date, 'YYYY/MM/DD HH24:MI:SS'/*'YYYY/MM/DD'*/) + 1
   ;
---- Obtener dia en fecha
SELECT TO_CHAR(SYSDATE,'D') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DAY'/*, 'NLS_DATE_LANGUAGE=SPANISH'*/) FROM DUAL;
  -- Obtener siguiente "Lunes" a partir de fecha
   SELECT NEXT_DAY(SYSDATE, 2) FROM DUAL;
   SELECT NEXT_DAY(SYSDATE,'LUNES') FROM DUAL;
---- Obtener semana desde fecha
SELECT TO_CHAR(SYSDATE, 'WW') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'IW') FROM DUAL;
---- Obtener mes desde fecha
SELECT TO_CHAR(SYSDATE, 'MM') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'MON'/*, 'NLS_DATE_LANGUAGE=SPANISH'*/) FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE=FRENCH') FROM DUAL;
---- Obtener año desde fecha
SELECT TO_CHAR(SYSDATE, 'YY') FROM DUAL;
---- Adicionar DIAS a Fecha
SELECT SYSDATE - 1 FROM DUAL;
---- Adicionar MESES a Fecha
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;
---- Obtener No. DIAS/SEMANAS/MESES entre Fecha1 & Fecha2
SELECT TO_DATE(&p_end_date, 'YYYY/MM/DD HH24:MI:SS') - TO_DATE(&p_start_date, 'YYYY/MM/DD HH24:MI:SS') AS No_dias FROM DUAL;
SELECT TRUNC(TO_NUMBER(TO_DATE(&p_end_date, 'YYYY/MM/DD HH24:MI:SS')-TO_DATE(&p_start_date, 'YYYY/MM/DD HH24:MI:SS'))/7) AS No_semanas FROM DUAL;
SELECT months_between(SYSDATE, SYSDATE - 55) FROM DUAL; --ROUND/TRUNC/CEIL/FLOOR
---- CONVERTIR Cadena de Texto a Fecha (Según el formato) NLS_DATE_LANGUAGE
SELECT TO_DATE('05-SEP-2007 10:00 PM','DD-MON-YYYY HH:MI AM') FROM DUAL;
SELECT TO_DATE('05-SEP-2007 10:00 AM','DD-MON-YYYY HH:MI AM') FROM DUAL;
SELECT TO_DATE('2007/09/05 12:45:00', 'YYYY/MM/DD HH:MI:SS') FROM DUAL;
SELECT TO_DATE('2007/09/05', 'YYYY/MM/DD') FROM DUAL;
SELECT TO_DATE('09/05/2011', 'MM/DD/YYYY') FROM DUAL;
---- CONVERTIR Cadena de Texto a Fecha (Según el formato)
    -----
    ALTER SESSION SET NLS_DATE_LANGUAGE= 'AMERICAN';
    SELECT TO_DATE('05-SEP-2007 10:00 PM','DD-MON-YYYY HH:MI AM') FROM DUAL;
    --
    SELECT TO_CHAR(TO_DATE('2011/08/01', 'YYYY/MM/DD'), 'MON-YYYY', 'NLS_DATE_LANGUAGE=spanish') FROM DUAL;
---- Extraer parte especificada para la fecha --[YEAR/MONTH/DAY/HOUR/MINUTE/SECOND]
SELECT EXTRACT(YEAR FROM SYSDATE)  FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE)   FROM DUAL;
SELECT EXTRACT(HOUR FROM SYSTIMESTAMP)   FROM DUAL; --?
SELECT EXTRACT(MINUTE FROM SYSTIMESTAMP) FROM DUAL; --?
SELECT EXTRACT(SECOND FROM SYSTIMESTAMP) FROM DUAL; --?
